# Generated by Django 2.2.3 on 2019-08-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_subcategoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'descripcion')},
        ),
    ]
